### ISSUE TITLE
tasks: reloadOnChange

### ISSUE THREAD

**Issue by Itamiko** [dirigeants/klasa-pieces#210]
lastest indev klasa
node: 11
```
TypeError: Cannot read property 'everything' of undefined
    at module.exports.run (/root/test/bnxytn987/src/tasks/reloadOnChange.js:30:17)
    at FSWatcher.reloadStore (/root/test/bnxytn987/src/tasks/reloadOnChange.js:57:28)
    at FSWatcher.emit (events.js:193:13)
    at FSWatcher.EventEmitter.emit (domain.js:481:20)
    at FSWatcher.emitWithAll (/root/test/bnxytn987/node_modules/chokidar/index.js:487:8)
    at FSWatcher._emit (/root/test/bnxytn987/node_modules/chokidar/index.js:577:10)
    at closer._watchWithNodeFs (/root/test/bnxytn987/node_modules/chokidar/lib/nodefs-handler.js:322:20)
```

**Comment by kyranet** [comment]
There's no such version as "indev" in Klasa, what branch are you using? `master`, `v1.0.0-alpha`, or `settings`?

**Comment by Itamiko** [comment]
master branch my bad

**Comment by kyranet** [comment]
Well, the code still exists...

https://github.com/dirigeants/klasa/blob/3360292f349cc791063a6b4dcb709080c486a1d8/src/commands/Admin/reload.js#L44-L59

I see no reason why should it throw, @gc is the author of that piece.

**Comment by gc** [comment]
Have you modified the `reload` command at all? Try `+eval this.client.commands.get('reload');` and see what it returns.

**Comment by Itamiko** [comment]
Nope haven’t modified core

**Output**:```js
Command {
  client: [LilyClient],
  file: [Array],
  name: 'reload',
  enabled: true,
  store: [CommandStore],
  directory: '/root/test/bnxytn987/node_modules/klasa/src/commands',
  aliases: [Array],
  requiredPermissions: [Permissions],
  deletable: false,
  description: [Function],
  extendedHelp: [Function],
  fullCategory: [Array],
  guarded: true,
  hidden: false,
  nsfw: false,
  permissionLevel: 10,
  promptLimit: 0,
  promptTime: 30000,
  quotedStringSupport: false,
  requiredSettings: [],
  runIn: [Array],
  subcommands: false,
  usage: [CommandUsage],
  cooldownLevel: 'author',
  cooldowns: RateLimitManager [Map] {} }```
**Type**:```ts
Command```
⏱ 65.38μs
