### ISSUE TITLE
pg provider timeout exceeded

### ISSUE THREAD

**Issue by Satont** [dirigeants/klasa-pieces#215]
When bot starts after while `pg` seems to be broke
```
[2019-09-08 01:39:38] Error: timeout exceeded when trying to connect
[2019-09-08 01:39:38]     at Timeout._onTimeout (/root/scripts/forgespirit/node_modules/pg-pool/index.js:180:27)
[2019-09-08 01:39:38]     at listOnTimeout (internal/timers.js:531:17)
[2019-09-08 01:39:38]     at processTimers (internal/timers.js:475:7)
```
Just spams this error in console

**Comment by Satont** [comment]
Version of pg `^7.12.1`

**Comment by favna** [comment]
Klasa is dead. The new framework is [Sapphire](https://github.com/sapphire-project/framework). You can join the Discord invite through this link: https://discord.com/invite/j8ACK6u
